alternate: HarmonyOS生活

sidebar:
  position: left
  avatar: avatar.jpg

menu:
  home: / || home
  about: 
    default: / || user
    aboutsite: /about/ || user  

reward:
  enable: true
  account:
    wechatpay: /wechatpay.jpg    